# config.py
import torch
from pathlib import Path

# --- Global Settings ---
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BASE_SAVE_DIR = Path("./results")

# --- Multi-Model Training Configurations ---
TRAINING_CONFIGS = {
    "MET_EMT_All": {
        "data_path": Path("./data/adata_MET_EMT_All.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "MET_EMT_All_model.pth",
        "time_column": "day",
        "is_sparse": False,
        "seed": 42,
        # Model Hyperparameters
        "hidden_dim": 1024,
        "num_blocks": 6,
        # Training Hyperparameters
        "batch_size": 3000,
        "epochs": 500,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        # Validation
        "val_epoch_start": 400,
        # Loss Weights
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "MET": {
        "data_path": Path("./data/adata_MET.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "MET_model.pth",
        "time_column": "day",
        "is_sparse": False,
        "seed": 42,
        "hidden_dim": 1024,
        "num_blocks": 6,
        "batch_size": 3000,
        "epochs": 500,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        "val_epoch_start": 400,
        "lambda_cvl": 1,
        "lambda_iso": 100,
    },
    "EMT": {
        "data_path": Path("./data/adata_EMT.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "EMT_model.pth",
        "time_column": "day",
        "is_sparse": False,
        "seed": 42,
        "hidden_dim": 1024,
        "num_blocks": 6,
        "batch_size": 3000,
        "epochs": 500,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        "val_epoch_start": 400,
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "Beta_Ec_All": {
        "data_path": Path("./data/adata_beta_ec_All.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "Beta_Ec_All.pth",
        "time_column": "CellDay",
        "is_sparse": False,
        "seed": 42,
        # Model Hyperparameters
        "hidden_dim": 1024,
        "num_blocks": 6,
        # Training Hyperparameters
        "batch_size": 4800,
        "epochs": 100,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        # Validation
        "val_epoch_start": -1,
        # Loss Weights
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "sc_ec": {
        "data_path": Path("./data/adata_ec.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "sc_ec_model.pth",
        "time_column": "CellDay",
        "is_sparse": False,
        "seed": 42,
        "hidden_dim": 1024,
        "num_blocks": 6,
        "batch_size": 4800,
        "epochs": 100,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        "val_epoch_start": -1,
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "sc_beta": {
        "data_path": Path("./data/adata_beta.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "sc_beta_model.pth",
        "time_column": "CellDay",
        "is_sparse": False,
        "seed": 42,
        "hidden_dim": 1024,
        "num_blocks": 6,
        "batch_size": 4800,
        "epochs": 100,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        "val_epoch_start": -1,
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "HSCs": {
        "data_path": Path("./data/adata_HSCs.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "HSCs_model.pth",
        "time_column": "day",
        "is_sparse": True, # 这个数据的 .X 是稀疏矩阵
        "seed": 42,
        "hidden_dim": 1024,
        "num_blocks": 6,
        "batch_size": 3000,
        "epochs": 1000,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 5e-2,
        'num_gap': 0,
        "val_epoch_start": 900,
        "lambda_cvl": 1.0,
        "lambda_iso": 100.0,
    },
    "MET_EMT_noiso": {
        "data_path": Path("./data/adata_MET_EMT_All.h5ad"),
        "save_path": BASE_SAVE_DIR / 'model' / "MET_EMT_noiso_model.pth",
        "time_column": "day",
        "is_sparse": False,
        "seed": 42,
        # Model Hyperparameters
        "hidden_dim": 1024,
        "num_blocks": 6,
        # Training Hyperparameters
        "batch_size": 3000,
        "epochs": 500,
        "learning_rate": 0.001,
        "lr_scheduler_t_max": 100,
        "lr_scheduler_eta_min": 1e-6,
        "grad_clip_max_norm": 1.0,
        'OT_REGULARIZATION': 1e-2,
        'num_gap': 2,
        # Validation
        "val_epoch_start": 400,
        # Loss Weights
        "lambda_cvl": 1.0,
        "lambda_iso": 0,
    }
}